heat_template_version: 2016-10-14

description: MS VNFC deployment templatea

parameter_groups:

parameters:
  vnfc_group:
    type: string
    default: Backends
  vnfi_id:
    type: string
    description: VNFI name
  index:
    type: number
    description: Heat ResourceGroup index.
  security_group:
    type: string
    description: Security Group (firewall rules) for all servers
  keypair:
    type: string
    description: SSH keypayr to inject in all servers
  site_code:
    type: string
    description: Short site name. For exampl SP, RJ, AMBA.
    default: AR
  time_zone_code:
    type: string
  timesync:
    type: string
    description: NTP server list.
  cca_config:
    type: string
    description: JSON of the form {"sites":[{"name":"siteName","cidr":"192.168.3.0/24","virtualIp":"192.168.3.50"},...]}
  image:
    type: string
    description: Image name or UUID.
  flavor:
    type: string
    description: Flavor name or UUID.
  om_net:
    type: string
    description: OM network
  om_subnet:
    type: string
    description: OM IP subnet
  om_mode:
    type: string
    description: static or dhcp
    constraints:
    - allowed_values:
      - static
      - dhcp
  om_netaddr:
    type: string
    description: OM network address.
  om_prefix:
    type: number
    description: OM network netmask prefix.
  om_gateway:
    type: string
    description: OM network default gateway.
  ssh_net:
    type: string
    description: OM ssh network
  ssh_subnet:
    type: string
    description: OM ssh network
  ssh_mode:
    type: string
    description: static or dhcp
    constraints:
    - allowed_values:
      - static
      - dhcp
  ssh_netaddr:
    type: string
    description: OM ssh network address.
  ssh_prefix:
    type: number
    description: OM ssh network netmask prefix.
  ssh_gateway:
    type: string
    description: OM ssh network gateway.
  db_password:
    type: string
    description: MySQL non root users password.
    default: Mcom@201811
  #server_group:
  #  type: string
  #  description: server group
  develop:
    type: boolean
    default: false
    description: Only for testing purpose.
  inter_site_nets:
    type: string
    description: name, site, cidr and gateway of every inter-site network
  do_signaling_routes:
    type: string
    description: false or true if signaling ip routes need to be done.
  local_quorum:
    type: number
  cca_ignite_multicast_group:
    type: string
    description: UDP multicast address to be used by CCA ignite cluster
  mgms_ignite_multicast_group:
    type: string
    description: UDP multicast address to be used by MGMS ignite cluster
  cdr_ignite_multicast_group:
    type: string
    description: UDP multicast address to be used by CDR ignite cluster
  nodes:
    type: json
    description: Array of nodes parameters, one for each index in HEAT ResourceGroup.
  networks:
    type: json
    label: Local Networks
    description: This POP networks information
  unica:
    type: boolean
    description: Set to True if deploying in UNICA environment}
    default: false
  vnfcnames:
    type: json
    label: Vnfc Names
    description: Vncf names renaming

conditions:

  is_unica:
    equals:
    - { get_param: unica }
    - True

  is_not_unica:
    not:
      equals:
      - { get_param: unica }
      - True

  ssh_is_static_unica:
    and:
    - equals:
      - { get_param: ssh_mode }
      - static
    - is_unica

  ssh_is_static_not_unica:
    and:
    - equals:
      - { get_param: ssh_mode }
      - static
    - is_not_unica

  ssh_is_dhcp_unica:
    and:
    - equals:
      - { get_param: ssh_mode }
      - dhcp
    - is_unica

  ssh_is_dhcp_not_unica:
    and:
    - equals:
      - { get_param: ssh_mode }
      - dhcp
    - is_not_unica

  with_floating_dhcp_unica:
    and:
      - equals:
        - { get_param: [ networks, PUBLIC, floating ] }
        - True
      - ssh_is_dhcp_unica

  with_floating_dhcp_not_unica:
    and:
      - equals:
        - { get_param: [ networks, PUBLIC, floating ] }
        - True
      - ssh_is_dhcp_not_unica

  with_floating_static_unica:
    and:
      - equals:
        - { get_param: [ networks, PUBLIC, floating ] }
        - True
      - ssh_is_static_unica

  with_floating_static_not_unica:
    and:
      - equals:
        - { get_param: [ networks, PUBLIC, floating ] }
        - True
      - ssh_is_static_not_unica

  om_is_static_unica:
    and:
    - equals:
      - { get_param: om_mode }
      - static
    - is_unica

  om_is_static_not_unica:
    and:
    - equals:
      - { get_param: om_mode }
      - static
    - is_not_unica

  om_is_dhcp_unica:
    and:
    - equals:
      - { get_param: om_mode }
      - dhcp
    - is_unica

  om_is_dhcp_not_unica:
    and:
    - equals:
      - { get_param: om_mode }
      - dhcp
    - is_not_unica

resources:

  padded_instance_number:
    type: OS::Heat::Value
    properties:
      type: string
      value:
        yaql:
          expression: selectCase(str($.data).len() = 1, str($.data).len() = 2).switchCase(format("00{0}",$.data),format("0{0}",$.data),str($.data))
          data: { get_param: [ nodes, get_param: index, instance ] }

  launch_script:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config: |
        #!/bin/bash
        nohup bash /mcom/.initialize/initialize.sh &
        exit 0

  files:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        debug: True
        ssh_pwauth: True
        disable_root: false
        chpasswd:
          list: |
            root:comviva01
            centos:comviva01
          expire: false
        runcmd:
        - sed -i'.orig' -e's/without-password/yes/' /etc/ssh/sshd_config
        - systemctl restart sshd
        write_files:
        - path: /tmp/configuration-data.sh
          content:
            str_replace:
              template: |
                export VNF='TSLEE'
                export VNFI='$VNFI'
                export VNFC='MS'
                export VNFC_GROUP='$VNFC_GROUP'
                export POP='$POP'
                export INSTANCE_NUMBER='$INSTANCE_NUMBER'
                export DEVELOP='$DEVELOP'
                export HOST_NAME='$HOST_NAME'
                export DOMAIN_NAME='$DOMAIN_NAME'
                export TIME_ZONE='$TIME_ZONE'
                export OMMODE='$OMMODE'
                export OMDEV='eth1'
                export OMADDR='$OMADDR'
                export OMNETADDR='$OMNETADDR'
                export OMPREFIX='$OMPREFIX'
                export OMGATEWAY='$OMGATEWAY'
                export BILLDEV=none
                export DBREPDEV=none
                export SIGDEV=none
                export CDRDEV=none
                export SSHMODE='$SSHMODE'
                export SSHDEV='eth0'
                export SSHADDR='$SSHADDR'
                export SSHNETADDR='$SSHNETADDR'
                export SSHPREFIX='$SSHPREFIX'
                export SSHGATEWAY='$SSHGATEWAY'
                export CCA_BOOTSTRAP='False'
                export DB_PASSWORD=$DB_PASSWORD
                export DO_SIGNALING_ROUTES='$DO_SIGNALING_ROUTES'
                export LOCAL_QUORUM='$LOCAL_QUORUM'
                export CCA_CLIENT='true'
                export CCA_THIN_CLIENT='true'
                export CCA_IGNITE_MULTICAST_GROUP='$CCA_IGNITE_MULTICAST_GROUP'
                export MGMS_IGNITE_MULTICAST_GROUP='$MGMS_IGNITE_MULTICAST_GROUP'
                export CDR_IGNITE_MULTICAST_GROUP='$CDR_IGNITE_MULTICAST_GROUP'
                export UNICA='$UNICA'
                export VNFC_RDBMS='$VNFC_RDBMS'
                export VNFC_TSLEE='$VNFC_TSLEE'
                export VNFC_MGMS='$VNFC_MGMS'
                export VNFC_CDR='$VNFC_CDR'
                export VNFC_GTW='$VNFC_GTW'
                export VNFC_DRA='$VNFC_DRA'
                export VNFC_SIPP='$VNFC_SIPP'
                export VNFC_IMDB='$VNFC_IMDB'
              params:
                $VNFI: { get_param: vnfi_id }
                $VNFC_GROUP: { get_param: vnfc_group }
                $POP: { get_param: site_code }
                $INSTANCE_NUMBER: { get_attr: [ padded_instance_number, value ] }
                $DEVELOP: { get_param: develop }
                $HOST_NAME: { get_param: [ nodes, get_param: index, hostname ] }
                $DOMAIN_NAME: { get_param: [ nodes, get_param: index, domain_name ] }
                $TIME_ZONE: { get_param: time_zone_code }
                $OMMODE: { get_param: om_mode }
                $OMADDR: { get_param: [ nodes, get_param: index, om ] }
                $OMNETADDR: { get_param: om_netaddr }
                $OMPREFIX: { get_param: om_prefix }
                $OMGATEWAY: { get_param: om_gateway }
                $SSHMODE: { get_param: ssh_mode }
                $SSHADDR: { get_param: [ nodes, get_param: index, ssh ] }
                $SSHNETADDR: { get_param: ssh_netaddr }
                $SSHPREFIX: { get_param: ssh_prefix }
                $SSHGATEWAY: { get_param: ssh_gateway }
                $DB_PASSWORD: { get_param: db_password }
                $DO_SIGNALING_ROUTES: { get_param: do_signaling_routes }
                $LOCAL_QUORUM: { get_param: local_quorum }
                $CCA_IGNITE_MULTICAST_GROUP: { get_param: cca_ignite_multicast_group }
                $MGMS_IGNITE_MULTICAST_GROUP: { get_param: mgms_ignite_multicast_group }
                $CDR_IGNITE_MULTICAST_GROUP: { get_param: cdr_ignite_multicast_group }
                $UNICA: { get_param: unica }
                $VNFC_RDBMS: { get_param: [ vnfcnames, RDBMS, name ] }
                $VNFC_TSLEE: { get_param: [ vnfcnames, TSLEE, name ] }
                $VNFC_MGMS: { get_param: [ vnfcnames, MGMS, name ] }
                $VNFC_CDR: { get_param: [ vnfcnames, CDR, name ] }
                $VNFC_GTW: { get_param: [ vnfcnames, GTW, name ] }
                $VNFC_DRA: { get_param: [ vnfcnames, DRA, name ] }
                $VNFC_SIPP: { get_param: [ vnfcnames, SIPP, name ] }
                $VNFC_IMDB: { get_param: [ vnfcnames, IMDB, name ] }
        - path: /tmp/timesync.json
          content: { get_param: timesync }
        - path: /tmp/cca-config.json
          content: { get_param: cca_config }
        - path: /mcom/.initialize/initialize-pre.sh
          permissions: '0755'
          content: |
            #!/bin/bash
            exit 0            
        - path: /mcom/.initialize/initialize-post.sh
          permissions: '0755'
          content: |
            #!/bin/bash
            HOSTNAME=$(hostname)
            sed -i -e "/^127.0.0.1/s/$/ $HOSTNAME/" -e "/^::1[ 	]/s/$/ $HOSTNAME/" /etc/hosts
            exit 0
        - path: /tmp/inter-site-routes.json
          content: { get_param: inter_site_nets }

  init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: files}
      - config: {get_resource: launch_script}

  server:
    type: OS::Nova::Server
    depends_on:
      - ssh_port_static_unica
      - ssh_port_static_not_unica
      - ssh_port_dhcp_unica
      - ssh_port_dhcp_not_unica
      - om_port_static_unica
      - om_port_static_not_unica
      - om_port_dhcp_unica
      - om_port_dhcp_not_unica
    properties:
      name:
        str_replace:
          template: $VNFI-MS-$INSTANCE_NUMBER
          params:
            $VNFI: { get_param: vnfi_id }
            $INSTANCE_NUMBER: { get_attr: [ padded_instance_number, value ] }
      key_name: { get_param: keypair }
      availability_zone: { get_param: [ nodes, get_param: index, availability_zone ] }
      scheduler_hints:
        #group: { get_param: server_group }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_attr: [ ssh_port_name, value ] }
        - port: { get_attr: [ om_port_name, value ] }
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_resource: init }
    
  ssh_port_name:
    type: OS::Heat::Value  
    properties:
      type: string
      value:
        str_replace:
          template: $VNFI-MS-$INSTANCE_NUMBER-ssh_port
          params:
            $VNFI: { get_param: vnfi_id }
            $INSTANCE_NUMBER: { get_attr: [ padded_instance_number, value ] }

  ssh_port_static_unica:
    type: OS::Neutron::Port
    condition: ssh_is_static_unica
    properties:
      name: { get_attr: [ ssh_port_name, value ] }
      network_id: { get_param: ssh_net }
      fixed_ips:
        - ip_address: { get_param: [ nodes, index, ssh ] }
      port_security_enabled: false

  ssh_port_static_not_unica:
    type: OS::Neutron::Port
    condition: ssh_is_static_not_unica
    properties:
      name: { get_attr: [ ssh_port_name, value ] }
      network_id: { get_param: ssh_net }
      fixed_ips:
        - ip_address: { get_param: [ nodes, get_param: index , ssh ] }
      security_groups: [ { get_param: security_group } ]

  floating_ip_static_unica:
    type: OS::Neutron::FloatingIP
    condition: with_floating_static_unica
    properties:
      floating_network: { get_param: [ networks, PUBLIC, netname ] }
      port_id: { get_resource: ssh_port_static_unica }

  floating_ip_static_not_unica:
    type: OS::Neutron::FloatingIP
    condition: with_floating_static_not_unica
    properties:
      floating_network: { get_param: [ networks, PUBLIC, netname ] }
      port_id: { get_resource: ssh_port_static_not_unica }

  ssh_port_dhcp_unica:
    type: OS::Neutron::Port
    condition: ssh_is_dhcp_unica
    properties:
      name: { get_attr: [ ssh_port_name, value ] }
      network_id: { get_param: ssh_net }
      fixed_ips:
        - subnet_id: { get_param: ssh_subnet }
      port_security_enabled: false

  ssh_port_dhcp_not_unica:
    type: OS::Neutron::Port
    condition: ssh_is_dhcp_not_unica
    properties:
      name: { get_attr: [ ssh_port_name, value ] }
      network_id: { get_param: ssh_net }
      fixed_ips:
        - subnet_id: { get_param: ssh_subnet }
      security_groups: [ { get_param: security_group } ]

  floating_ip_dhcp_unica:
    type: OS::Neutron::FloatingIP
    condition: with_floating_dhcp_unica
    properties:
      floating_network: { get_param: [ networks, PUBLIC, netname ] }
      port_id: { get_resource: ssh_port_dhcp_unica }

  floating_ip_dhcp_not_unica:
    type: OS::Neutron::FloatingIP
    condition: with_floating_dhcp_not_unica
    properties:
      floating_network: { get_param: [ networks, PUBLIC, netname ] }
      port_id: { get_resource: ssh_port_dhcp_not_unica }

  om_port_name:
    type: OS::Heat::Value
    properties:
      type: string
      value:
        str_replace:
          template: $VNFI-MS-$INSTANCE_NUMBER-om_port
          params:
            $VNFI: { get_param: vnfi_id }
            $INSTANCE_NUMBER: { get_attr: [ padded_instance_number, value ] }

  om_port_static_unica:
    type: OS::Neutron::Port
    condition: om_is_static_unica
    properties:
      name: { get_attr: [ om_port_name, value ] }
      network_id: { get_param: om_net }
      fixed_ips:
        - ip_address: { get_param: [ nodes, get_param: index, om ] }
      port_security_enabled: false

  om_port_static_not_unica:
    type: OS::Neutron::Port
    condition: om_is_static_not_unica
    properties:
      name: { get_attr: [ om_port_name, value ] }
      network_id: { get_param: om_net }
      fixed_ips:
        - ip_address: { get_param: [ nodes, get_param: index, om ] }
      security_groups: [ { get_param: security_group } ]

  om_port_dhcp_unica:
    type: OS::Neutron::Port
    condition: om_is_dhcp_unica
    properties:
      name: { get_attr: [ om_port_name, value ] }
      network_id: { get_param: om_net }
      fixed_ips:
        - subnet_id: { get_param: om_subnet }
      port_security_enabled: false

  om_port_dhcp_not_unica:
    type: OS::Neutron::Port
    condition: om_is_dhcp_not_unica
    properties:
      name: { get_attr: [ om_port_name, value ] }
      network_id: { get_param: om_net }
      fixed_ips:
        - subnet_id: { get_param: om_subnet }
      security_groups: [ { get_param: security_group } ]
