name: Base structure  Deploy

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OS_AUTH_URL: '${{ secrets.OS_AUTH_URL }}'
  OS_PASSWORD: '${{ secrets.OS_PASSWORD }}'
  OS_PASSWORD_INPUT: '${{ secrets.OS_PASSWORD_INPUT }}'
  OS_PROJECT_ID: '${{ secrets.OS_PROJECT_ID }}'
  OS_USERNAME: '${{ secrets.OS_USERNAME }}'



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Set Up OpenStack deploy API
      run: |
        export OS_AUTH_URL= "$OS_AUTH_URL"
        export OS_IDENTITY_API_VERSION=3
        export OS_INTERFACE=public
        export OS_PASSWORD= ${{ secrets.OS_PASSWORD }}
        export OS_PASSWORD_INPUT= ${{ secrets.OS_PASSWORD_INPUT }}
        export OS_PROJECT_DOMAIN_ID=default
        export OS_PROJECT_ID= ${{ secrets.OS_PROJECT_ID }}
        export OS_PROJECT_NAME=admin
        export OS_REGION_NAME=IAD3
        export OS_USERNAME= ${{ secrets.OS_USERNAME }}
        export OS_USER_DOMAIN_NAME=Default



    - name: Deploy Terraform
      run: |
        directories=("deploy-networks-eir flavors-eir routers-eir")
        for dir in $directories
        do
          if [[ -f "${dir}/main.tf" ]]; then
            echo "Deploying in directory: $dir"
            cd "$dir"
            terraform init \
              -backend-config="bucket=${BUCKET_NAME}" \
              -backend-config="key=tf-openstack/terraform.tfstate" \
              -backend-config="region=us-east-1"
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
            cd ..
          fi
        done

