name: Terraform Deploy

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Deploy Terraform
      run: |
        directories=("deploy-image deploy-vm")
        for dir in $directories
        do
          if [[ -f "${dir}main.tf" ]]; then
            echo "Deploying in directory: $dir"
            cd "$dir"
            terraform init \
              -backend-config="bucket=${BUCKET_NAME}" \
              -backend-config="key=tf-openstack/terraform.tfstate" \
              -backend-config="region=us-east-1"
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
            cd ..
          fi
        done

